---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: java
    tag: '8'

inputs:
  - name: moviefun

run:
  path: moviefun/ci/tasks/integration.sh
  args: [
    --input-dir, moviefun
  ]
